#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=space_changed action="sketchybar --trigger windows_on_spaces"

# global settings
yabai -m config external_bar               all:35:0     \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_origin_display      default      \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              off          \
                window_opacity             on           \
                window_opacity_duration    0.3          \
                window_animation_duration  0.4          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.80         \
                active_window_border_color 0xff7aa2f7   \
                normal_window_border_color 0x80565f89   \
                insert_feedback_color      0x00d75f5f   \
                window_border              on           \
                window_border_width        1            \
                window_border_radius       12           \
                window_border_blur         on           \
                window_border_hidpi        off          \
                split_ratio                0.50         \
                split_type                 auto         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                8            \
                bottom_padding             8            \
                left_padding               8            \
                right_padding              8            \
                window_gap                 4            \

# Exclude problematic apps from being managed:
yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="Stats" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=on manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Digital Colour Meter$" sticky=on manage=off
yabai -m rule --add app="Raycast" sticky=on manage=off
yabai -m rule --add app="^zoom\.us$" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
